on:
  push:
    branches:
      - master

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: tests

jobs:
  install:
    name: Test scripts

    runs-on: ubuntu-latest

    container:
      image: rocker/geospatial:4.1.2

    steps:
      - name: Before build
        run: bash ./bk-config.sh

      - name: Build redirect
        run: Rscript ./bk-install.R
