on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: tests

jobs:
  install:
    name: Test scripts

    runs-on: ubuntu-latest

    container:
      image: rocker/geospatial:4.1.2

    steps:
      - name: ls
        run: ls
        shell: bash

      - name: bk-config.sh
        run: sh bk-config.sh
        shell: bash

      - name: bk-install.R
        run: Rscript bk-install.R
        shell: bash
