on:
  push:
    branches:
      - master

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: tests

jobs:
  bookdown:
    name: Test scripts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          crayon.enabled: "FALSE"
          r-version: "4.1.2"

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Before build
        run: bash ./bk-config.sh

      - name: Build redirect
        run: Rscript ./bk-install.R
